# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sam Thompson
tagline:          'Frontend Web Developer'
description:      'Web developer in Chicago, previously at IG and Razorfish in London'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sam Thompson'
  url:            https://twitter.com/samteeeee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
