# Dependencies
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sam T
tagline:          'Frontend Web Developer'
description:      'Web developer in Chicago, previously at IG and Razorfish in London'
url:              http://sammydigits.github.com
baseurl:          /
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-53416544-1

author:
  name:           'Sam Thompson'
  url:            https://twitter.com/sammydigits

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samteeeee/samteeeee.github.io
